# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.network "forwarded_port", guest: 3000, host: 13000
  config.vm.synced_folder "./provisioning", "/vagrant_provisioning"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
 
  config.vm.provision "shell", privileged: true ,inline: <<-SHELL
    apt-get update
    apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev -y
  SHELL

  config.vm.provision "shell", privileged: false ,inline: <<-SHELL
    chmod +x /vagrant_provisioning/*
    /vagrant_provisioning/ruby.sh
    /vagrant_provisioning/node.sh
  SHELL

end
