# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.network "forwarded_port", guest: 28017, host: 28017
  config.vm.synced_folder "./provisioning", "/vagrant_provisioning"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
 
  config.vm.provision "shell", privileged: true ,inline: <<-SHELL
    /vagrant_provisioning/mongodb.sh
  SHELL

  config.vm.provision "shell", privileged: false ,inline: <<-SHELL
    #chmod +x /vagrant_provisioning/*
    #/vagrant_provisioning/ruby.sh
  SHELL

end
