# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.network "forwarded_port", guest: 9200, host: 19200
  config.vm.network "forwarded_port", guest: 9300, host: 19300
  config.vm.synced_folder "./provisioning", "/vagrant_provisioning"

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
 
  config.vm.provision "shell", privileged: true ,inline: <<-SHELL
    chmod +x /vagrant_provisioning/*
    /vagrant_provisioning/java8.sh
    /vagrant_provisioning/elasticsearch.sh
  SHELL

  config.vm.provision "shell", privileged: false ,inline: <<-SHELL

  SHELL

end
